#! /usr/bin/env bash
set -eu

FILENAME=$1

cd /data

if [[ "$FILENAME" == *.sql ]]; then
    mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE" < "$FILENAME"
elif [[ "$FILENAME" == *.sql.gz ]]; then
    zcat "$FILENAME" | mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE"
elif [[ "$FILENAME" == *.sql.zst ]]; then
    zstd -d -c "$FILENAME" | mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE"
elif [[ "$FILENAME" == *.zip ]]; then
    unzip -p "$FILENAME" | mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE"
else
    echo "Unknown file format"
fi
